#!/bin/bash

CP="lib/jewelcli-0.6.jar:lib/libthrift.jar:thrift/gen-java.jar:lib/slf4j-api-1.5.8.jar:lib/slf4j-simple-1.5.8.jar:lib/org-netbeans-swing-outline.jar:lib/tightvnc.jar:bin/:lib/jedis-2.1.0.jar:lib/commons-pool-1.5.5.jar"
DECKLINK_CP=:magiclib/magiclib.jar:magiclib/jna.jar
DECKLINK_JNA=-Djna.library.path=magiclib
DECKLINK_PATH=-Djava.library.path=magiclib

# For windows
if [ "`uname -o`" = "Cygwin" ]; then
    CP="$(echo "$CP" | sed 's/:/;/g' | sed 's+/+\\+g')"
    export PATH=$PATH:/cygdrive/c/Program\ Files\ \(x86\)/VideoLAN/VLC/
fi

if [ "$1" == "build" ]; then
  mkdir -p bin
  javac -d bin -sourcepath src -cp "$CP" $(find src -name '*.java')
else
  java -Xmx1000m $JVM_ARGS -cp "$CP$DECKLINK_CP" $DECKLINK_JNA $DECKLINK_PATH se.kth.livetech.communication.LiveClient "$@"
fi
